# Generated by Django 5.1.1 on 2024-11-05 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Municipio',
            new_name='Municipios',
        ),
    ]
