# Generated by Django 5.1.1 on 2024-11-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema1', '0002_rename_municipio_municipios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipios',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Municipios'),
        ),
    ]
