# Generated by Django 5.1.1 on 2024-11-06 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema1', '0003_alter_municipios_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.IntegerField()),
                ('descripcion', models.IntegerField()),
                ('total', models.IntegerField()),
                ('documento', models.FileField(upload_to='ruta')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sistema1.municipios')),
            ],
            options={
                'db_table': 'Convenios',
            },
        ),
    ]
