# Generated by Django 5.1.1 on 2024-11-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema1', '0004_convenios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='convenios',
            name='documento',
            field=models.FileField(upload_to='convenios/'),
        ),
        migrations.AlterField(
            model_name='convenios',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
