# Generated by Django 5.1.1 on 2024-11-28 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema1', '0005_alter_convenios_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenios',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='Sistema1.municipios'),
        ),
        migrations.CreateModel(
            name='HistorialConvenios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('total', models.IntegerField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='historial_convenios/')),
                ('convenio_madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Sistema1.convenios')),
            ],
            options={
                'db_table': 'HistorialConvenios',
                'ordering': ['-fecha_modificacion'],
            },
        ),
    ]
